phrase:
  project_id: 02f8f3eb9dabfb0aa81565e94a450a78
  pull:
    targets:
    - file: ./Snabble/<locale_name>.lproj/Localizable.strings
      params:
        file_format: strings
        encoding: "UTF-8"
        fallback_locale_id: 8a496aa8b2a5b608340772cdac21a04f
        include_empty_translations: true
        format_options:
            convert_placeholder: true
            include_pluralized_keys: false
    - file: ./Snabble/<locale_name>.lproj/Localizable.stringsdict
      params:
        file_format: stringsdict
        encoding: "UTF-8"
        fallback_locale_id: 8a496aa8b2a5b608340772cdac21a04f
        include_empty_translations: true
        format_options:
            convert_placeholder: true
