included:
 - Snabble

disabled_rules:
 - todo
 - cyclomatic_complexity
 - type_body_length
 - line_length
 - function_body_length
 - file_length

opt_in_rules:
 - private_outlet
 - private_action
 - array_init
 - convenience_type
 - discouraged_object_literal
 - empty_collection_literal
 - empty_count
 - empty_string
 - explicit_init
 - legacy_multiple
 - legacy_random
 - literal_expression_end_indentation
 - modifier_order
 - multiline_function_chains
 - operator_usage_whitespace
 - override_in_extension
 - redundant_type_annotation
 - toggle_bool
 - unused_import
 - yoda_condition

identifier_name:
  min_length: 3
  excluded:
  - id
  - on
  - ok
  - nc
  - db
  - dx
  - dy
  - iv
  - dm
