source 'https://cdn.cocoapods.org/'
deployment_target = '14.0'
platform :ios, deployment_target
use_frameworks!
inhibit_all_warnings!

target 'SnabbleSampleApp' do
  pod 'Snabble', :path => '../'
end

post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = deployment_target
      end
    end

    project.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = deployment_target
    end
  end
end
