deployment_target = '14.0'
platform :ios, deployment_target
use_frameworks!
inhibit_all_warnings!

plugin 'cocoapods-pod-sign'

target 'SnabbleSampleApp' do
  pod 'Snabble', :path => '../', :inhibit_warnings => false
  pod 'Snabble/Datatrans', :path => '../'
end

post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = deployment_target
      end

      if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
        target.build_configurations.each do |config|
          puts "Bundle Fix for Xcode 14 of target: #{target.name}"
          config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
          config.build_settings['PRODUCT_BUNDLE_IDENTIFIER'] = "org.cocoapods.#{target.product_name}"
        end
      end
    end

    project.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = deployment_target
    end
  end
end
