podspec: Snabble.podspec
theme: fullwidth 
skip_undocumented: true
readme: README.md
documentation: documentation/*.md
hide_documentation_coverage: true
author: Snabble
author_url: https://snabble.io/
github_url: https://github.com/Snabble/iOS-SDK
module: Snabble
source_directory: ./Snabble
