phrase:
  project_id: 12f8a92f13729d6f1996d5bce9ff7cbe
  pull:
    targets:
    - file: ./Snabble/UI/<locale_name>.lproj/SnabbleLocalizable.strings
      params:
        file_format: strings
        tags: "SDK"
        encoding: "UTF-8"
        fallback_locale_id: eb9f9cf6ff99449945836ece05d93833
        include_empty_translations: true
        format_options:
            convert_placeholder: true
            include_pluralized_keys: false
    - file: ./Snabble/UI/<locale_name>.lproj/SnabbleLocalizable.stringsdict
      params:
        file_format: stringsdict
        tags: "SDK"
        encoding: "UTF-8"
        fallback_locale_id: eb9f9cf6ff99449945836ece05d93833
        include_empty_translations: true
        format_options:
            convert_placeholder: true
