phrase:
  project_id: 3e43b3f90cf19e83c7d85652df5766ca
  pull:
    targets:
    - file: ./Snabble/UI/<locale_name>.lproj/Localizable.strings
      params:
        file_format: strings
        tags: "SDK"
        encoding: "UTF-8"
        fallback_locale_id: b220db5757be359631c55ec54fb65ac6
        include_empty_translations: true
        format_options:
            convert_placeholder: true
            include_pluralized_keys: false
    - file: ./Snabble/UI/<locale_name>.lproj/Localizable.stringsdict
      params:
        file_format: stringsdict
        tags: "SDK"
        encoding: "UTF-8"
        fallback_locale_id: b220db5757be359631c55ec54fb65ac6
        include_empty_translations: true
        format_options:
            convert_placeholder: true
