phrase:
  pull:
    targets:
    - file: ./Sources/UI/Resources/<locale_name>.lproj/Localizable.strings
      project_id: 3e43b3f90cf19e83c7d85652df5766ca
      params:
        file_format: strings
        encoding: "UTF-8"
        fallback_locale_id: b220db5757be359631c55ec54fb65ac6
        include_empty_translations: true
        format_options:
            convert_placeholder: true
            include_pluralized_keys: false
    - file: ./Sources/UI/Resources/<locale_name>.lproj/Localizable.stringsdict
      project_id: 3e43b3f90cf19e83c7d85652df5766ca
      params:
        file_format: stringsdict
        encoding: "UTF-8"
        fallback_locale_id: b220db5757be359631c55ec54fb65ac6
        include_empty_translations: true
        format_options:
            convert_placeholder: true
    - file: ./Example/Snabble/<locale_name>.lproj/Localizable.strings
      project_id: 02f8f3eb9dabfb0aa81565e94a450a78
      params:
        file_format: strings
        encoding: "UTF-8"
        fallback_locale_id: 8a496aa8b2a5b608340772cdac21a04f
        include_empty_translations: true
        format_options:
            convert_placeholder: true
            include_pluralized_keys: false
    - file: ./Example/Snabble/<locale_name>.lproj/Localizable.stringsdict
      project_id: 02f8f3eb9dabfb0aa81565e94a450a78
      params:
        file_format: stringsdict
        encoding: "UTF-8"
        fallback_locale_id: 8a496aa8b2a5b608340772cdac21a04f
        include_empty_translations: true
        format_options:
            convert_placeholder: true
            
      
