included:
 - Sources
 - Example/Snabble

disabled_rules:
 - todo
 - cyclomatic_complexity
 - type_body_length
 - line_length
 - function_body_length
 - file_length
 - trailing_whitespace
 - multiple_closures_with_trailing_closure
 - function_parameter_count

opt_in_rules:
 - private_outlet
 - private_action
 - array_init
 - convenience_type
 - discouraged_object_literal
 - empty_collection_literal
 - empty_count
 - empty_string
 - explicit_init
 - legacy_multiple
 - legacy_random
 - literal_expression_end_indentation
 - multiline_function_chains
 - operator_usage_whitespace
 - override_in_extension
 - toggle_bool
 - yoda_condition

nesting:
  type_level: 2

type_name:
  max_length: 45

identifier_name:
  min_length: 3
  excluded:
  - id
  - on
  - db
  - ok
  - ca
  - nc
  - to
  - mc
  - qr
  - up
  - iv
  - ai
  - gs
  - in
  - x
  - y
  - _self
