on:
  push:
    branches: [ main ]
  pull_request:
    paths:
      - '.github/workflows/lint.yml'
      - '.swiftlint.yml'
      - '**/*.swift'

env:
  DEVELOPER_DIR: /Applications/Xcode_14.0.app/Contents/Developer
  MINT_PATH: ${{ github.workspace }}/mint

name: Danger
jobs:
  SDK:
    name: Danger
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Danger
        uses: docker://ghcr.io/danger/danger-swift-with-swiftlint:3.14.0
        with:
            args: -b main --failOnErrors --no-publish-check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  TEST:
    name: Danger
    runs-on: macos-12
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Danger
        run: npm install -g danger

      - name: Install Danger-Swift
        run: brew install danger/tap/danger-swift

      - name: Install Mint
        run: brew install mint

      - name: Cache Mint packages
        uses: actions/cache@v3
        with:
          path: ${{ env.MINT_PATH }}
          key: ${{ runner.os }}-mint-${{ hashFiles('**/Mintfile') }}
          restore-keys: ${{ runner.os }}-mint-
      
      - name: Bootstrap
        run: mint bootstrap

      - name: Danger
        run: mint run danger/swift locale -b main --failOnErrors --no-publish-check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
