on:
  push:
    branches: [ main ]
  pull_request:
    paths:
      - '.github/workflows/lint.yml'
      - '.swiftlint.yml'
      - '**/*.swift'

env:
  MINT_PATH: ${{ github.workspace }}/mint

name: Danger
jobs:
  SDK:
    name: Danger
    runs-on: macos-12
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # - name: Cache npm dependencies
      #   uses: actions/cache@v2
      #   with:
      #     path: node_modules
      #     key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      #     restore-keys: |
      #       ${{ runner.os }}-node-

      - name: NPM install
        run: npm install -g danger

      - name: Cache Mint packages
        uses: actions/cache@v3
        with:
          path: ${{ env.MINT_PATH }}
          key: ${{ runner.os }}-mint-${{ hashFiles('**/Mintfile') }}
          restore-keys: ${{ runner.os }}-mint-

      - name: Install Mint
        run: brew install mint

      - name: Mint bootstrap
        run: mint bootstrap

      # - name: Danger
      #   uses: danger/swift@3.14.0
      #   with:
      #       args: -b main --failOnErrors --no-publish-check
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Danger
        run: mint run danger/swift ci -b main
  # Sample:
  #   name: Sample
  #   runs-on: macos-12
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3

  #     - name: Cache npm dependencies
  #       uses: actions/cache@v2
  #       with:
  #         path: node_modules
  #         key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
  #         restore-keys: |
  #           ${{ runner.os }}-node-

  #     - name: NPM Install
  #       run: npm install

  #     - name: Cache Mint packages
  #       uses: actions/cache@v3
  #       with:
  #         path: ${{ env.MINT_PATH }}
  #         key: ${{ runner.os }}-mint-${{ hashFiles('**/Mintfile') }}
  #         restore-keys: ${{ runner.os }}-mint-

  #     - name: Install Mint
  #       run: brew install mint

  #     - name: Bootstrap
  #       run: mint bootstrap

  #     - name: Danger
  #       run: |
  #         cd Example
  #         mint run danger/swift ci -b main
