on: workflow_dispatch

env:
  DEVELOPER_DIR: /Applications/Xcode_13.2.app/Contents/Developer

name: Documenation
jobs:
  lint:
    name: Documenation
    runs-on: macos-11
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Set ImageVersion environment variable
        run: echo "ImageVersion=$ImageVersion"  >> $GITHUB_ENV

      - name: Gem Cache
        uses: actions/cache@v2
        with:
          path: main/vendor/bundle
          key: ${{ runner.os }}-gems-${{ env.ImageVersion }}-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: ${{ runner.os }}-gems-${{ env.ImageVersion }}
      
      - name: Bundler
        run: |
          cd main
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Jazzy
        run: bundle exec jazzy -c

      - name: Commit
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: documenation update
        branch: gh-pages
        file_pattern: docs/**

      - name: Slack Notification
        uses: lazy-actions/slatify@master
        if: always()
        with:
          type: ${{ job.status }}
          job_name: '*iOS SDK Documenation*'
          username: 'Github Action: Documenation'
          channel: '#app-actions'
          url: ${{ secrets.SLACK_WEBHOOK }}
