on: workflow_dispatch

env:
  DEVELOPER_DIR: /Applications/Xcode_13.2.app/Contents/Developer

name: Lint
jobs:
  lint:
    name: Lint
    runs-on: macos-11
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Jazzy
        run: bundle exec jazzy -c

      - name: Slack Notification
        uses: lazy-actions/slatify@master
        if: always()
        with:
          type: ${{ job.status }}
          job_name: '*iOS SDK Documenation*'
          username: 'Github Action: Documenation'
          channel: '#app-actions'
          url: ${{ secrets.SLACK_WEBHOOK }}
