on:
  workflow_dispatch:
  push:
    tags:
      - "**"

name: Pay Documentation
jobs:
  docc:
    name: DocC
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Xcode Plugin
        run: defaults write com.apple.dt.Xcode IDESkipPackagePluginFingerprintValidatation -bool YES

      - name: Build Documentation
        run: xcodebuild docbuild -scheme SnabblePay -destination 'generic/platform=iOS' -derivedDataPath ${{ runner.temp }}/docc

      - name: Static Website
        run: $(xcrun --find docc) process-archive transform-for-static-hosting ${{ runner.temp }}/docc/Build/Products/Debug-iphoneos/SnabblePay.doccarchive --output-path ./docs --hosting-base-path snabble-pay-ios-sdk

      - name: Zip
        run: zip -r static-website.zip ./docs

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: documentation
          path: static-website.zip

  deploy:
    name: Deploy GitHub Page
    runs-on: ubuntu-latest
    needs: DocC
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: documentation

      - name: Unzip
        run: unzip static-website.zip -d ./

      - name: GitHub Pages Deploy
        uses: Cecilapp/GitHub-Pages-deploy@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          email: info@snabble.io
          build_dir: docs
          branch: gh-pages
          commit_message: update documentation
