on: 
  workflow_dispatch:
  push:
    tags:
      - 0.*

env:
  DEVELOPER_DIR: /Applications/Xcode_13.2.app/Contents/Developer

name: Documentation
jobs:
  jazzy:
    name: Jazzy
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Set ImageVersion environment variable
        run: echo "ImageVersion=$ImageVersion"  >> $GITHUB_ENV

      - name: Gem Cache
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ env.ImageVersion }}-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: ${{ runner.os }}-gems-${{ env.ImageVersion }}
      
      - name: Bundler
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Jazzy
        run: bundle exec jazzy -c

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: documentation
          path: docs

  deploy:
    name: Deploy GitHub Page
    runs-on: ubuntu-latest
    needs: Jazzy
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: documentation
          path: docs
      
      - name: GitHub Pages Deploy
        uses: Cecilapp/GitHub-Pages-deploy@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          email: info@snabble.io
          build_dir: docs
          branch: gh-pages
          commit_message: update documentation

      - name: Slack Notification
        uses: lazy-actions/slatify@master
        if: always()
        with:
          type: ${{ job.status }}
          job_name: '*iOS SDK Documenation*'
          username: 'Github Action: Documenation'
          channel: '#app-actions'
          url: ${{ secrets.SLACK_WEBHOOK }}
