on: 
  workflow_dispatch:
  push:
    tags:
      - '**'

env:
  DEVELOPER_DIR: /Applications/Xcode_14.0.1.app/Contents/Developer

name: Documentation
jobs:
  docc:
    name: DocC
    runs-on: macos-12
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build Documentation
        run: xcodebuild docbuild -scheme SnabbleSDK-Package -destination 'platform=iOS Simulator,name=iPhone 14' -derivedDataPath ${{ runner.temp }}/derivedDataPath

      - name: Static Website Core
        run: $(xcrun --find docc) process-archive transform-for-static-hosting ${{ runner.temp }}/derivedDataPath/Build/Products/Debug-iphonesimulator/SnabbleCore.doccarchive --output-path ./static-website/core --hosting-base-path /snabble-ios-sdk/core

      - name: Static Website UI
        run: $(xcrun --find docc) process-archive transform-for-static-hosting ${{ runner.temp }}/derivedDataPath/Build/Products/Debug-iphonesimulator/SnabbleUI.doccarchive --output-path ./static-website/ui --hosting-base-path /snabble-ios-sdk/ui
        
      - name: Zip
        run: zip -r static-website.zip static-website

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: documentation
          path: static-website.zip

  deploy:
    name: Deploy GitHub Page
    runs-on: ubuntu-latest
    needs: DocC
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: documentation

      - name: Unzip
        run: unzip static-website.zip -d ./
      
      - name: GitHub Pages Deploy
        uses: Cecilapp/GitHub-Pages-deploy@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          email: info@snabble.io
          build_dir: static-website
          branch: gh-pages
          commit_message: update documentation
