on: 
  workflow_dispatch:
  push:
    tags:
      - 0.*

env:
  DEVELOPER_DIR: /Applications/Xcode_13.2.app/Contents/Developer

name: Documenation
jobs:
  lint:
    name: Documenation
    runs-on: macos-11
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Set ImageVersion environment variable
        run: echo "ImageVersion=$ImageVersion"  >> $GITHUB_ENV

      - name: Gem Cache
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ env.ImageVersion }}-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: ${{ runner.os }}-gems-${{ env.ImageVersion }}
      
      - name: Bundler
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Jazzy
        run: bundle exec jazzy -c

      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: docs
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Slack Notification
        uses: lazy-actions/slatify@master
        if: always()
        with:
          type: ${{ job.status }}
          job_name: '*iOS SDK Documenation*'
          username: 'Github Action: Documenation'
          channel: '#app-actions'
          url: ${{ secrets.SLACK_WEBHOOK }}
