on: 
  workflow_dispatch:
  push:
    tags:
      - '**'

env:
  DEVELOPER_DIR: /Applications/Xcode_14.0.1.app/Contents/Developer

name: Documentation
jobs:
  docc:
    name: DocC
    runs-on: macos-12
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build Documentation
        run: xcodebuild docbuild -scheme SnabbleSDK-Package -destination 'platform=iOS Simulator,name=iPhone 14' -derivedDataPath ./generated-documentation

      - name: Static Website
        run: $(xcrun --find docc) process-archive transform-for-static-hosting ./generated-documentation/Build/Products/Debug-iphonesimulator/SnabbleCore.doccarhive --output-path ./static-website --hosting-base-path snabble.github.io/snabble-ios-sdk/

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: documentation
          path: static-website

  deploy:
    name: Deploy GitHub Page
    runs-on: ubuntu-latest
    needs: DocC
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: documentation
          path: static-website
      
      - name: GitHub Pages Deploy
        uses: Cecilapp/GitHub-Pages-deploy@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          email: info@snabble.io
          build_dir: static-website
          branch: gh-pages
          commit_message: update documentation
