on:
  workflow_dispatch:
  push:
    tags:
      - "**"

name: Snabble Documentation
jobs:
  docc:
    name: docc
    runs-on: macos-latest # https://github.com/actions/runner-images
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - name: Checkout
        uses: actions/checkout@v4

      - name: Xcode Plugin
        run: defaults write com.apple.dt.Xcode IDESkipPackagePluginFingerprintValidatation -bool YES

      - name: Build Documentation
        run: xcodebuild docbuild -scheme Snabble -destination 'generic/platform=iOS' -derivedDataPath ${{ runner.temp }}/derivedDataPath

      - name: Create static-website folder
        run: mkdir static-website

      - name: Static Website Core
        run: $(xcrun --find docc) process-archive transform-for-static-hosting ${{ runner.temp }}/derivedDataPath/Build/Products/Debug-iphoneos/SnabbleCore.doccarchive --output-path ./static-website/core --hosting-base-path /snabble-ios-sdk/core

      - name: Static Website UI
        run: $(xcrun --find docc) process-archive transform-for-static-hosting ${{ runner.temp }}/derivedDataPath/Build/Products/Debug-iphoneos/SnabbleUI.doccarchive --output-path ./static-website/ui --hosting-base-path /snabble-ios-sdk/ui

      - name: Build Documentation
        run: xcodebuild docbuild -scheme SnabblePay -destination 'generic/platform=iOS' -derivedDataPath ${{ runner.temp }}/derivedDataPath

      - name: Static Website Pay
        run: $(xcrun --find docc) process-archive transform-for-static-hosting ${{ runner.temp }}/derivedDataPath/Build/Products/Debug-iphoneos/SnabblePay.doccarchive --output-path ./static-website/pay --hosting-base-path /snabble-ios-sdk/pay

      - name: Zip
        run: zip -r static-website.zip static-website

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Documentation
          path: static-website.zip

  deploy:
    name: Deploy GitHub Page
    runs-on: ubuntu-latest
    needs: docc
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: Documentation

      - name: Unzip
        run: unzip static-website.zip -d ./

      - name: GitHub Pages Deploy
        uses: Cecilapp/GitHub-Pages-deploy@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          email: info@snabble.io
          build_dir: static-website
          branch: gh-pages
          commit_message: Update documentation
