on:
  pull_request:
    paths:
      - '.github/workflows/lint.yml'
      - '.swiftlint.yml'
      - 'Dangerfile.swift'
      - '**/*.swift'

name: Review
jobs:
  SDK:
    name: Review
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: SwiftLint
        uses: sinoru/actions-swiftlint@v6
        with:
          swiftlint-version: '0.49.1'
          swiftlint-args: --config .swiftlint.yml

      - name: Danger
        uses: danger/swift@3.14.2
        with:
            args: -b main --failOnErrors --no-publish-check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


