# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  Test:
    runs-on: macos-14
    env:
      DEVELOPER_DIR: /Applications/Xcode_16_1.app/Contents/Developer

    steps:
      - uses: actions/checkout@v4
      - name: Test Network
        run: xcodebuild -scheme Snabble-Package -destination 'platform=iOS Simulator,name=iPhone 16,OS=18.0' test
